import type { PresetDefinition } from "@/types/settings";

export const presets: PresetDefinition[] = [
  {
    id: "frontend",
    name: "フロントエンド",
    description: "npm コマンド許可、src 編集 acceptEdits 設定",
    category: "frontend",
    settings: {
      permissions: {
        allow: [
          { tool: "Bash", command: "npm test" },
          { tool: "Bash", command: "npm run *" },
          { tool: "Read", path: "**/*" },
          { tool: "Edit", path: "src/**" },
        ],
        deny: [
          { tool: "Bash", command: "npm publish" },
          { tool: "Read", path: ".env" },
          { tool: "Read", path: "**/.env" },
          { tool: "Read", path: "**/.env.*" },
          { tool: "Edit", path: ".env" },
          { tool: "Edit", path: "**/.env" },
          { tool: "Edit", path: "**/.env.*" },
        ],
        ask: [
          { tool: "Bash", command: "npm install *" },
          { tool: "Bash", command: "npx *" },
          { tool: "Edit", path: "package.json" },
        ],
      },
      permissionMode: "acceptEdits",
    },
  },
  {
    id: "hardened-security",
    name: "Hardened Security",
    description: "デフォルト Ask、機密パスへの絶対・相対 Deny ルール強制",
    category: "security",
    settings: {
      permissions: {
        allow: [],
        deny: [
          { tool: "Read", path: ".env" },
          { tool: "Read", path: "**/.env" },
          { tool: "Read", path: "**/.env.*" },
          { tool: "Read", path: "//.env" },
          { tool: "Edit", path: ".env" },
          { tool: "Edit", path: "**/.env" },
          { tool: "Edit", path: "**/.env.*" },
          { tool: "Edit", path: "//.env" },
          { tool: "Read", path: "//.ssh/**" },
          { tool: "Edit", path: "//.ssh/**" },
          { tool: "Read", path: "//.aws/credentials" },
          { tool: "Edit", path: "//.aws/credentials" },
          { tool: "Read", path: "**/*.key" },
          { tool: "Read", path: "**/*.pem" },
          { tool: "Edit", path: "**/*.key" },
          { tool: "Edit", path: "**/*.pem" },
          { tool: "Bash", command: "rm -rf *" },
        ],
        ask: [
          { tool: "Bash", command: "git push *" },
          { tool: "Bash", command: "curl *" },
          { tool: "Bash", command: "wget *" },
        ],
      },
      permissionMode: "default",
    },
  },
  {
    id: "vibe-coding",
    name: "Vibe Coding",
    description: "サンドボックス強制有効化 + auto モード推奨",
    category: "experimental",
    settings: {
      permissions: {
        allow: [
          { tool: "Edit", path: "src/**" },
          { tool: "Edit", path: "app/**" },
          { tool: "Bash", command: "npm *" },
          { tool: "Bash", command: "yarn *" },
          { tool: "Bash", command: "pnpm *" },
        ],
        deny: [
          { tool: "Read", path: ".env" },
          { tool: "Read", path: "**/.env" },
          { tool: "Edit", path: ".env" },
          { tool: "Edit", path: "**/.env" },
        ],
        ask: [{ tool: "Bash", command: "git push *" }],
      },
      permissionMode: "auto",
      sandbox: {
        enabled: true,
        allowedHosts: ["localhost", "127.0.0.1"],
      },
    },
  },
  {
    id: "python-backend",
    name: "Python バックエンド",
    description: "pytest / mypy / ruff 許可、pip publish 拒否",
    category: "backend",
    settings: {
      permissions: {
        allow: [
          { tool: "Bash", command: "python -m pytest *" },
          { tool: "Bash", command: "python -m mypy *" },
          { tool: "Bash", command: "python -m ruff *" },
          { tool: "Bash", command: "pip install -e ." },
          { tool: "Edit", path: "src/**" },
          { tool: "Edit", path: "app/**" },
          { tool: "Edit", path: "**/*.py" },
        ],
        deny: [
          { tool: "Bash", command: "pip publish *" },
          { tool: "Bash", command: "twine upload *" },
          { tool: "Read", path: ".env" },
          { tool: "Read", path: "**/.env" },
          { tool: "Edit", path: ".env" },
          { tool: "Edit", path: "**/.env" },
        ],
        ask: [
          { tool: "Bash", command: "python *.py" },
          { tool: "Bash", command: "pip install *" },
          { tool: "Edit", path: "requirements*.txt" },
          { tool: "Edit", path: "pyproject.toml" },
        ],
      },
      permissionMode: "acceptEdits",
    },
  },
  {
    id: "go-backend",
    name: "Go バックエンド",
    description: "go test / build / vet 許可",
    category: "backend",
    settings: {
      permissions: {
        allow: [
          { tool: "Bash", command: "go test *" },
          { tool: "Bash", command: "go build *" },
          { tool: "Bash", command: "go vet *" },
          { tool: "Edit", path: "**/*.go" },
        ],
        deny: [
          { tool: "Read", path: ".env" },
          { tool: "Read", path: "**/.env" },
          { tool: "Edit", path: ".env" },
          { tool: "Edit", path: "**/.env" },
        ],
        ask: [
          { tool: "Bash", command: "go run *" },
          { tool: "Bash", command: "go get *" },
          { tool: "Bash", command: "go install *" },
          { tool: "Edit", path: "go.mod" },
          { tool: "Edit", path: "go.sum" },
        ],
      },
      permissionMode: "acceptEdits",
    },
  },
  {
    id: "rust",
    name: "Rust",
    description: "cargo test / build / clippy / fmt 許可",
    category: "backend",
    settings: {
      permissions: {
        allow: [
          { tool: "Bash", command: "cargo test *" },
          { tool: "Bash", command: "cargo build *" },
          { tool: "Bash", command: "cargo clippy *" },
          { tool: "Bash", command: "cargo fmt *" },
          { tool: "Edit", path: "src/**/*.rs" },
        ],
        deny: [
          { tool: "Bash", command: "cargo publish *" },
          { tool: "Read", path: ".env" },
          { tool: "Read", path: "**/.env" },
          { tool: "Edit", path: ".env" },
          { tool: "Edit", path: "**/.env" },
        ],
        ask: [
          { tool: "Bash", command: "cargo run *" },
          { tool: "Bash", command: "cargo add *" },
          { tool: "Edit", path: "Cargo.toml" },
        ],
      },
      permissionMode: "acceptEdits",
    },
  },
  {
    id: "laravel",
    name: "Laravel",
    description: "php artisan / composer 許可、.env・DB破壊系コマンドは制御",
    category: "backend",
    settings: {
      permissions: {
        allow: [
          { tool: "Bash", command: "php artisan test *" },
          { tool: "Bash", command: "php artisan make:*" },
          { tool: "Bash", command: "php artisan route:list *" },
          { tool: "Bash", command: "php artisan config:cache *" },
          { tool: "Bash", command: "php artisan config:clear *" },
          { tool: "Bash", command: "php artisan cache:clear *" },
          { tool: "Bash", command: "php artisan view:clear *" },
          { tool: "Bash", command: "composer install" },
          { tool: "Bash", command: "composer dump-autoload *" },
          { tool: "Edit", path: "app/**" },
          { tool: "Edit", path: "resources/**" },
          { tool: "Edit", path: "routes/**" },
          { tool: "Edit", path: "tests/**" },
          { tool: "Edit", path: "database/migrations/**" },
          { tool: "Edit", path: "database/seeders/**" },
          { tool: "Edit", path: "database/factories/**" },
        ],
        deny: [
          { tool: "Read", path: ".env" },
          { tool: "Read", path: "**/.env" },
          { tool: "Read", path: "**/.env.*" },
          { tool: "Edit", path: ".env" },
          { tool: "Edit", path: "**/.env" },
          { tool: "Edit", path: "**/.env.*" },
          { tool: "Bash", command: "php artisan down *" },
        ],
        ask: [
          { tool: "Bash", command: "php artisan migrate" },
          { tool: "Bash", command: "php artisan migrate:*" },
          { tool: "Bash", command: "php artisan db:seed *" },
          { tool: "Bash", command: "composer require *" },
          { tool: "Bash", command: "composer update *" },
          { tool: "Edit", path: "composer.json" },
          { tool: "Edit", path: "config/**" },
        ],
      },
      permissionMode: "acceptEdits",
    },
  },
  {
    id: "laravel-sail",
    name: "Laravel Sail",
    description: "sail コマンド許可、artisan/composer は sail 経由で制御",
    category: "backend",
    settings: {
      permissions: {
        allow: [
          { tool: "Bash", command: "./vendor/bin/sail up *" },
          { tool: "Bash", command: "./vendor/bin/sail down *" },
          { tool: "Bash", command: "./vendor/bin/sail artisan test *" },
          { tool: "Bash", command: "./vendor/bin/sail artisan make:*" },
          { tool: "Bash", command: "./vendor/bin/sail artisan route:list *" },
          { tool: "Bash", command: "./vendor/bin/sail artisan config:cache *" },
          { tool: "Bash", command: "./vendor/bin/sail artisan config:clear *" },
          { tool: "Bash", command: "./vendor/bin/sail artisan cache:clear *" },
          { tool: "Bash", command: "./vendor/bin/sail artisan view:clear *" },
          { tool: "Bash", command: "./vendor/bin/sail composer install" },
          { tool: "Bash", command: "./vendor/bin/sail composer dump-autoload *" },
          { tool: "Bash", command: "./vendor/bin/sail npm *" },
          { tool: "Bash", command: "./vendor/bin/sail shell *" },
          { tool: "Edit", path: "app/**" },
          { tool: "Edit", path: "resources/**" },
          { tool: "Edit", path: "routes/**" },
          { tool: "Edit", path: "tests/**" },
          { tool: "Edit", path: "database/migrations/**" },
          { tool: "Edit", path: "database/seeders/**" },
          { tool: "Edit", path: "database/factories/**" },
        ],
        deny: [
          { tool: "Read", path: ".env" },
          { tool: "Read", path: "**/.env" },
          { tool: "Read", path: "**/.env.*" },
          { tool: "Edit", path: ".env" },
          { tool: "Edit", path: "**/.env" },
          { tool: "Edit", path: "**/.env.*" },
          { tool: "Bash", command: "./vendor/bin/sail artisan down *" },
        ],
        ask: [
          { tool: "Bash", command: "./vendor/bin/sail artisan migrate" },
          { tool: "Bash", command: "./vendor/bin/sail artisan migrate:*" },
          { tool: "Bash", command: "./vendor/bin/sail artisan db:seed *" },
          { tool: "Bash", command: "./vendor/bin/sail composer require *" },
          { tool: "Bash", command: "./vendor/bin/sail composer update *" },
          { tool: "Edit", path: "composer.json" },
          { tool: "Edit", path: "config/**" },
          { tool: "Edit", path: "docker-compose.yml" },
        ],
      },
      permissionMode: "acceptEdits",
    },
  },
  // ── Addon Presets ──────────────────────────────
  {
    id: "git-operations",
    name: "Git Operations",
    description: "git 全般を許可し、commit / push は確認を要求",
    category: "addon",
    type: "addon",
    settings: {
      permissions: {
        allow: [{ tool: "Bash", command: "git *" }],
        deny: [],
        ask: [
          { tool: "Bash", command: "git commit *" },
          { tool: "Bash", command: "git push *" },
        ],
      },
    },
  },
  {
    id: "docker-operations",
    name: "Docker Operations",
    description: "docker / docker compose コマンドを許可、破壊系は確認",
    category: "addon",
    type: "addon",
    settings: {
      permissions: {
        allow: [
          { tool: "Bash", command: "docker ps *" },
          { tool: "Bash", command: "docker logs *" },
          { tool: "Bash", command: "docker compose up *" },
          { tool: "Bash", command: "docker compose down *" },
          { tool: "Bash", command: "docker build *" },
        ],
        deny: [],
        ask: [
          { tool: "Bash", command: "docker rm *" },
          { tool: "Bash", command: "docker rmi *" },
          { tool: "Bash", command: "docker system prune *" },
          { tool: "Bash", command: "docker push *" },
        ],
      },
    },
  },
];
